version: '3.8'

volumes:
  ollama_storage:
    driver: local
    driver_opts:
      type: none
      device: D:\MCP\n8n-data\ollama
      o: bind

networks:
  shared_network:
    driver: bridge

x-ollama: &service-ollama
  image: ollama/ollama:latest
  container_name: ollama
  networks: ['shared_network']
  restart: unless-stopped
  ports:
    - 11434:11434
  volumes:
    - ollama_storage:/root/.ollama

x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  networks: ['shared_network']
  container_name: ollama-pull-llama
  volumes:
    - ollama_storage:/root/.ollama
  entrypoint: /bin/sh
  environment:
    - OLLAMA_HOST=ollama:11434
  command:
    - "-c"
    - "sleep 3; ollama run phi4-mini:3.8b-q4_K_M"

services:
  ollama-cpu:
    profiles: ["cpu"]
    <<: *service-ollama

  ollama-pull-llama-cpu:
    profiles: ["cpu"]
    <<: *init-ollama
    depends_on:
      - ollama-cpu